### ISSUE TITLE
When playing as Tielaxu, in revival stage other factions do not revive

### ISSUE THREAD

**Issue by goodygoodygoody90** [ronaldossendrijver/treachery.online#16]
After I increase revival limits and progress to revival stage, factions do not complete revivals. 

![dune](https://github.com/ronaldossendrijver/treachery.online/assets/165560500/b13f14c7-e233-492d-88dc-9cec54dc01b2)

**Comment by ronaldossendrijver** [comment]
Hi! Do you perhaps still have a savegame so i can analyse?

**Comment by goodygoodygoody90** [comment]
Hi Ronald,

Thanks for looking into this. I've attached a saved file both just before and after the bidding phase.

Thanks,
James
________________________________

**Comment by ronaldossendrijver** [comment]
I think I know what happened here. As you can see in the screenshot, Fremen did a request to be allowed to revive Stilgar, but you haven't denied or approved that request yet. All bots wait until all outstanding revival requests have been answered before reviving.

I think I can change this so that in a way that bots only wait until their own request has been answered.
